# configuration for https://travis-ci.org/ulordj/ulordj
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
install: true # remove default
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#ulordj"
    skip_join: true
