/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bitcoin_hello_CryptoHelloContext */

#ifndef _Included_org_bitcoin_hello_CryptoHelloContext
#define _Included_org_bitcoin_hello_CryptoHelloContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitcoin_hello_CryptoHelloContext
 * Method:    helloHash
 * Signature: ([BJ[B)V
 */
JNIEXPORT void JNICALL Java_org_bitcoin_hello_CryptoHelloContext_helloHash
  (JNIEnv *, jclass, jbyteArray, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
